module.exports = (function () {
	function getRandomInt(min, max) {
		return Math.floor(Math.random() * (max - min) + min);
	}

	var books = [],
		book = require('./book.js');

	var titles = [
		'The Flames',
		'Darkness',
		'Gone',
		'Lost',
		'Too good to be true',
		'I loved you',
		'My heart',
		'Smoke',
		'The black fog',
		'The Girl',
		'Broken',
		'Red',
		'Heal me',
		'Hope',
		'The chip',
		'Millionaire (or Billionaire)',
		'More Crap',
		'My manic life',
		'Unglued',
		'The Chronicle',
		'San Francisco',
		'New York',
		'December',
		'The night everything fell apart',
		'The swim',
		'Ocean',
		'Desert',
		'Ice',
		'Forever Mine',
		'No Winter',
		'The End',
		'Theif',
		'The Rainbow',
		'Ways to say goodbye',
		'Shooting Star',
		'No Gold',
		'Silver Night',
		'Serenity',
		'Chicken Noodle Soup',
		'Our Souls Entwined',
		'Sweet and Sour',
		'Poison',
		'Forgive and Forget',
		'Never Again',
		'Neverland',
		'Don\'t forget me',
		'Forest',
		'The Cinemas',
		'Gun',
		'Forever alone',
		'Halfway',
		'My journey',
		'Siblings',
		'Powerful',
		'The Words',
		'Bleeding Heart',
		'Blood',
		'Sustenance',
		'White Van',
		'Almost there',
		'Double zero',
		'Lost but found',
		'Man Overboard',
		'In Trouble',
		'The Last Time',
		'Please, God',
		'Mother Nature',
		'Six Figures',
		'Savages',
		'Save',
		'The Cheat',
		'The Breakout',
		'Never Give Up',
		'Hollow',
		'Unfair Games',
		'Debt',
		'Bloody Moon',
		'My life, your life, our lives',
		'Twenty-one',
		'The Check',
		'Your Mistake',
		'Timber',
		'Her eyes',
		'Wreath',
		'Countdown',
		'My Voice',
		'Burning Hell',
		'Inspiration',
		'Velvet Tears',
		'Pointless Numbers',
		'Neon City',
		'Dark Light',
		'Black Thunder',
		'Heartbreak',
		'Holiday Disaster',
		'So Close',
		'The Ring',
		'The Book',
		'Misconception',
		'Karma',
	];

	var authors = ["Shakespeare, William", "Christie, Agatha", "Cartland, Barbara", "Steel, Danielle", "Robbins, Harold", "Simenon, Georges", "Sheldon, Sidney", "Blyton, Enid", "Seuss, Dr.", "Patten, Gilbert", "Rowling, J. K.", "Tolstoy, Leo", "Tellado, Corín", "Collins, Jackie", "Alger, Jr., Horatio", "Stine, R. L.", "Koontz, Dean", "Roberts, Nora", "Pushkin, Alexander", "King, Stephen", "L'Amour, Louis", "Gardner, Erle Stanley", "Akagawa, Jirō", "Dailey, Janet", "Wallace, Edgar", "Ludlum, Robert", "Patterson, James", "Dard, Frédéric", "Archer, Jeffrey", "Berenstain, Stan and Jan", "Grisham, John", "Grey, Zane", "Wallace, Irving", "Tolkien, J. R. R.", "May, Karl", "Spillane, Mickey", "Lewis, C. S.", "Nishimura, Kyotaro", "Brown, Dan", "Martin, Ann M.", "Shiba, Ryōtarō", "Hailey, Arthur", "Villiers, Gérard de", "Potter, Beatrix", "Crichton, Michael", "Scarry, Richard", "Cussler, Clive", "MacLean, Alistair", "Follett, Ken", "Lindgren, Astrid", "Macomber, Debbie", "Coelho, Paulo", "Yoshikawa, Eiji", "Cookson, Catherine", "Meyer, Stephenie", "Bridwell, Norman", "Baldacci, David", "Dahl, Roald", "Hunter, Evan", "Neiderman, Andrew", "Hargreaves, Roger", "Rice, Anne", "Cook, Robin", "Smith, Wilbur", "Caldwell, Erskine", "Hibbert, Eleanor", "Carroll, Lewis", "Robins, Denise", "Xueqin, Cao", "Fleming, Ian", "Hesse, Hermann", "Stout, Rex", "Golon, Anne", "Slaughter, Frank G.", "Burroughs, Edgar Rice", "Creasey, John", "Michener, James", "Uchida, Yasuo", "Morimura, Seiichi", "Higgins Clark, Mary", "Jordan, Penny", "Cornwell, Patricia", "Clancy, Tom"];

	for (var i = 0, len = titles.length; i < len; i += 1) {
		books.push(Object.create(book).init(titles[getRandomInt(0,titles.length)],authors[getRandomInt(0,authors.length)]));
	}
	
	return books;
} ())